version: 2
updates:
  - package-ecosystem: "npm"
    directory: "code/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "docker"
    directory: "code/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
