version: '3'

services:
  nodejs:
    build: .
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}