version: '3.2'

services:
  mongo:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    logging:
      driver: "none"