version: "3.9"
services:
  mongodb:
    # build: ./mongodb
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: always
    expose:
      - 27017
      - 37017
    ports:
      - 27017:27017
      - 37017:37017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    networks:
      - default
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
    logging:
      driver: "none"

  mongodb-seed:
    build: ./mongodb
    hostname: seed-mongodb
    container_name: seed-mongodb
    networks:
      - default
    depends_on:
      - mongodb

  graphdb:
    image: neo4j
    hostname: graphdb
    container_name: graphdb
    volumes:
      - ./neo4j/data:/datasets
    expose:
      - 7687
      - 7474
    ports:
      - 7687:7687
      - 7474:7474
    networks:
      - default
    environment:
    #  - NEO4J_AUTH=neo4j/fistic
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes