version: 2
updates:
  - package-ecosystem: "npm"
    directory: "code/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
